# Generated by Django 4.2.3 on 2023-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teaccher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField()),
                ('t_name', models.CharField(max_length=40)),
                ('t_email', models.EmailField(max_length=30)),
            ],
        ),
    ]
